canton {
  sequencers {
    globalSequencer {
      public-api { address = "0.0.0.0", port = 5001 }
      admin-api  { address = "0.0.0.0", port = 5002 }
      storage.type = memory
    }
  }
  mediators {
    globalMediator {
      admin-api { address = "0.0.0.0", port = 5202 }
      storage.type = memory
    }
  }
  participants {
    participantNode1 {
      ledger-api      { address = "0.0.0.0", port = 5011 }
      admin-api       { address = "0.0.0.0", port = 5012 }
      http-ledger-api { address = "0.0.0.0", port = 7575 }
      storage.type = memory
    }
  }
}
